import jsPDF from 'jspdf'

const SEVERITY_COLORS = {
  critical: [220, 38, 38],
  high: [217, 119, 6],
  medium: [217, 119, 6],
  low: [2, 132, 199],
}

const SEVERITY_LABELS = {
  critical: 'CRITICAL',
  high: 'HIGH',
  medium: 'MEDIUM',
  low: 'LOW',
}

export function generatePDF(findings, summary, overallRisk) {
  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.getWidth()
  const margin = 20
  const contentWidth = pageWidth - margin * 2
  let y = 20

  doc.setFillColor(15, 17, 23)
  doc.rect(0, 0, pageWidth, 45, 'F')

  doc.setTextColor(255, 255, 255)
  doc.setFontSize(20)
  doc.setFont('helvetica', 'bold')
  doc.text('ScreenShield', margin, 22)

  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(156, 163, 175)
  doc.text('Security Analysis Report', margin, 32)

  const date = new Date().toLocaleString()
  doc.text(`Generated: ${date}`, pageWidth - margin, 32, { align: 'right' })

  y = 60

  const riskColor = SEVERITY_COLORS[overallRisk] || [22, 163, 74]
  doc.setFillColor(...riskColor)
  doc.roundedRect(margin, y - 8, 60, 14, 3, 3, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(9)
  doc.setFont('helvetica', 'bold')
  doc.text(`${(SEVERITY_LABELS[overallRisk] || 'CLEAN')} RISK`, margin + 6, y + 1)

  doc.setTextColor(15, 17, 23)
  doc.setFontSize(22)
  doc.setFont('helvetica', 'bold')
  doc.text(`${findings.length} Threat${findings.length !== 1 ? 's' : ''} Detected`, margin, y + 22)

  y += 40

  const gridItems = [
    { label: 'Critical', count: summary.critical, color: [220, 38, 38] },
    { label: 'High', count: summary.high, color: [217, 119, 6] },
    { label: 'Medium', count: summary.medium, color: [217, 119, 6] },
    { label: 'Low', count: summary.low, color: [2, 132, 199] },
  ]

  const cellWidth = contentWidth / 4
  gridItems.forEach((item, i) => {
    const cellX = margin + i * cellWidth
    doc.setFillColor(245, 246, 250)
    doc.roundedRect(cellX, y, cellWidth - 4, 24, 3, 3, 'F')
    doc.setTextColor(...item.color)
    doc.setFontSize(16)
    doc.setFont('helvetica', 'bold')
    doc.text(String(item.count), cellX + cellWidth / 2 - 2, y + 13, { align: 'center' })
    doc.setFontSize(8)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(156, 163, 175)
    doc.text(item.label, cellX + cellWidth / 2 - 2, y + 21, { align: 'center' })
  })

  y += 36

  doc.setDrawColor(229, 231, 235)
  doc.line(margin, y, pageWidth - margin, y)
  y += 12

  doc.setTextColor(15, 17, 23)
  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')
  doc.text('Findings', margin, y)
  y += 10

  const sorted = [...findings].sort((a, b) => {
    const rank = { critical: 4, high: 3, medium: 2, low: 1 }
    return (rank[b.severity] || 0) - (rank[a.severity] || 0)
  })

  for (const finding of sorted) {
    if (y > 250) {
      doc.addPage()
      y = 20
    }

    const color = SEVERITY_COLORS[finding.severity] || [2, 132, 199]

    doc.setFillColor(249, 250, 251)
    doc.roundedRect(margin, y, contentWidth, 44, 4, 4, 'F')

    doc.setFillColor(...color)
    doc.roundedRect(margin + 8, y + 6, 28, 9, 2, 2, 'F')
    doc.setTextColor(255, 255, 255)
    doc.setFontSize(7)
    doc.setFont('helvetica', 'bold')
    doc.text(SEVERITY_LABELS[finding.severity] || '', margin + 12, y + 12)

    doc.setTextColor(15, 17, 23)
    doc.setFontSize(10)
    doc.setFont('helvetica', 'bold')
    doc.text(finding.name.replace(/[^\x00-\x7F]/g, ''), margin + 42, y + 12)

    doc.setFillColor(229, 231, 235)
    doc.roundedRect(margin + 8, y + 18, contentWidth - 16, 10, 2, 2, 'F')
    doc.setTextColor(55, 65, 81)
    doc.setFontSize(8)
    doc.setFont('courier', 'normal')
    const displayText = finding.matchedText.length > 70
      ? finding.matchedText.slice(0, 35) + '...' + finding.matchedText.slice(-25)
      : finding.matchedText
    doc.text(displayText.replace(/[^\x00-\x7F]/g, ''), margin + 12, y + 25)

   doc.setFont('helvetica', 'normal')
    doc.setTextColor(107, 114, 128)
    doc.setFontSize(8)
    // Strip special characters that jsPDF can't render
    const cleanRemediation = finding.remediation
      .replace(/→/g, '>')
      .replace(/[^\x00-\x7F]/g, '')
    const remLines = doc.splitTextToSize(cleanRemediation, contentWidth - 24)
    if (remLines.length > 1) {
      doc.text(remLines[0], margin + 8, y + 34)
      doc.text(remLines[1], margin + 8, y + 41)
    } else {
      doc.text(remLines[0], margin + 8, y + 37)
    }

    y += 62
  }

  const footerY = doc.internal.pageSize.getHeight() - 12
  doc.setDrawColor(229, 231, 235)
  doc.line(margin, footerY - 4, pageWidth - margin, footerY - 4)
  doc.setTextColor(156, 163, 175)
  doc.setFontSize(8)
  doc.setFont('helvetica', 'normal')
  doc.text('Generated by ScreenShield', margin, footerY)
  doc.text('Page 1', pageWidth - margin, footerY, { align: 'right' })

  doc.save(`ScreenShield-report-${Date.now()}.pdf`)
}

export async function generateRedactedImage(imageFile, findings, imageDimensions) {
  return new Promise((resolve) => {
    const img = new Image()
    const url = URL.createObjectURL(imageFile)

    img.onload = () => {
      const canvas = document.createElement('canvas')
      canvas.width = imageDimensions.width
      canvas.height = imageDimensions.height

      const ctx = canvas.getContext('2d')

      // Draw original image
      ctx.drawImage(img, 0, 0)

      // Draw redaction bars over each finding
      for (const finding of findings) {
        if (!finding.bbox) continue

        const { x0, y0, x1, y1 } = finding.bbox
        const width = x1 - x0
        const height = y1 - y0

        if (width <= 0 || height <= 0) continue

        // Black redaction bar with padding
        const padding = 3
        ctx.fillStyle = '#000000'
        ctx.fillRect(
          x0 - padding,
          y0 - padding,
          width + padding * 2,
          height + padding * 2
        )
      }

      // Watermark
      ctx.fillStyle = 'rgba(0,0,0,0.35)'
      ctx.fillRect(0, imageDimensions.height - 28, imageDimensions.width, 28)
      ctx.fillStyle = '#FFFFFF'
      ctx.font = '11px sans-serif'
      ctx.fillText(
        `Redacted by ScreenShield — ${new Date().toLocaleDateString()}`,
        10,
        imageDimensions.height - 10
      )

      URL.revokeObjectURL(url)

      canvas.toBlob((blob) => {
        const link = document.createElement('a')
        link.href = URL.createObjectURL(blob)
        link.download = `redacted-screenshot-${Date.now()}.png`
        link.click()
        resolve()
      }, 'image/png')
    }

    img.src = url
  })
}